runs_dir: 'runs'

# experiment_name: experiments_v2
experiment_name: benchmarks_v2
# experiment_name: ablations

run_name: '[${dataset.name}]/[${model.model_name}]/${experiment_name:${model.decoder.type}}'
group_name: ''
save_dir: '${run.runs_dir}/${run.experiment_name}/${run.run_name}/${run.group_name}'

