max_epochs: 700

accelerator: cpu
devices: 1
num_workers: 2

check_val_every_n_epoch: 10

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False