# @package _global_
defaults:
  - _self_

model:
  model_name: iaunet-r50
  type: iaunet

  # model params.
  encoder: null
    
  decoder:  
    # pixel decoder config.
    type: iadecoder_ml
    n_levels: 4

    mask_branch:
      type: MaskStackedConv # opt: MaskDoubleConv, MaskStackedConv
      dim: 256
      num_convs: 2

    instance_branch:
      type: InstStackedConv # opt: InstDoubleConv, InstStackedConv
      dim: 256
      num_convs: 2
    
    # transformer decoder config.
    num_queries: 100
    num_classes: 1
    hidden_dim: 256
    nheads: 8
    dec_layers: 1   # transfomer decoder layers per model decoder layer.
    dropout: 0.1
    pre_norm: false
    dim_feedforward: 2048


  # model loading and saving.
  load_pretrained: false
  ckpt_path: ''
  save_checkpoint: true
  save_model_files: true
  load_from_files: false
  model_files: ''

  # model training params.
  solver:
    optimizer:
      type: AdamW
      lr: 0.0001
      weight_decay: 0.05
    backbone_lr_multiplier: 0.1
    embedding_weight_decay: 0.0

  scheduler:
    type: CosineAnnealingLR
    eta_min: 1.0e-06
    T_max: 16000
    verbose: false



  criterion:
    type: SparseCriterion
    losses:
      - labels
      - masks
      # - activations
      # - bboxes
    weights:
      labels: 1.0
      bce_masks: 5.0
      dice_masks: 2.0
      iou_masks: 2.0
      bbox_weight: 5.0
      giou_weight: 2.0
      no_object_weight: 0.1
    matcher:
      type: PointSampleHungarianMatcher
      cost_cls: 1.0
      cost_dice: 2.0
      cost_mask: 5.0
      cost_bbox: 5.0
      cost_giou: 2.0
      num_points: 12544
    num_classes: 1

  evaluator:
    type: MMDetDataloaderEvaluator
    mask_thr: 0.5
    score_thr: 0.01
    nms_thr: 0.8
    metric: segm
    classwise: true
    outfile_prefix: results/coco
