# @package _global_
defaults:
 - model/default
 - _self_

model:
  type: iaunet
  in_channels: 3
  num_classes: 1
  n_levels: 4

  encoder: null
  decoder: null

  load_pretrained: false
  weights: ''
  # TODO: to callbacks
  save_checkpoint: true
  save_model_files: true
  load_from_files: false
  model_files: ''

  optimizer:
    type: AdamW
    lr: 0.0001
    weight_decay: 0.05

  scheduler:
    type: CosineAnnealingLR
    eta_min: 1.0e-06
    T_max: 16000
    verbose: false
