# # @package _global_

# instance_head:
#   type: InstanceHead-v1.1
#   # type: InstanceHead-v2.0-attn
#   in_channels: 256
#   num_classes: 1
#   kernel_dim: 256
#   num_masks: 100
#   num_groups: 1
#   activation: softmax