# @package _global_
dataset:
  name: ISBI2014
  type: ISBI2014

  data_root: /project/project_465001327/datasets/ISBI2014/coco
  # data_root:  /gpfs/space/projects/PerkinElmer/cytoplasm_segmentation/datasets/ISBI2014/coco

  train_dataset:
    images: ${dataset.data_root}/isbi_train
    ann_file: ${dataset.data_root}/annotations/isbi_train.json
    size: [512, 512]
    batch_size: 8
    augmentation: lsj
    return_masks: true
    return_bboxes: true
    return_labels: true
    filter_empty: true
    min_bbox_size: 1.0
    use_crowd: false

  # valid_dataset:
  #   images: ${dataset.data_root}/isbi_val
  #   ann_file: ${dataset.data_root}/annotations/isbi_val.json
  #   size: [512, 512]
  #   batch_size: 8

  valid_dataset:
    images: ${dataset.data_root}/isbi_test
    ann_file: ${dataset.data_root}/annotations/isbi_test.json
    size: [512, 512]
    batch_size: 8
    return_masks: true
    return_bboxes: true
    return_labels: true

  eval_dataset:
    images: ${dataset.data_root}/isbi_test
    ann_file: ${dataset.data_root}/annotations/isbi_test.json
    size: [512, 512]
    batch_size: 8
    return_masks: true
    return_bboxes: true
    return_labels: true

  mean: [221.65, 221.65, 221.65]
  std: [25.28, 25.28, 25.28]