# @package _global_
dataset:
  name: NeurlPS22_CellSeg
  type: NeurlPS22_CellSeg

  data_root: /gpfs/space/projects/PerkinElmer/cytoplasm_segmentation/datasets/NeurlPS22-CellSeg/coco_new

  train_dataset:
    images: ${dataset.data_root}/images
    ann_file: ${dataset.data_root}/annotations/train.json
    size: [512, 512]
    batch_size: 8

  valid_dataset:
    images: ${dataset.data_root}/images
    ann_file: ${dataset.data_root}/annotations/valid.json
    size: [512, 512]
    batch_size: 8

  eval_dataset:
    images: ${dataset.data_root}/images
    ann_file: ${dataset.data_root}/annotations/test.json
    size: [512, 512]
    batch_size: 8

  mean: [145, 145, 145]
  std: [40, 40, 40]