# @package _global_
dataset:
  name: Revvity_25
  type: Revvity_25

  # data_root: /project/project_465001327/datasets/Revvity-25
  data_root: /gpfs/space/projects/PerkinElmer/cytoplasm_segmentation/datasets/Revvity-25/v2

  train_dataset:
    images: ${dataset.data_root}/images
    ann_file: ${dataset.data_root}/annotations/train.json
    size: [512, 512]
    batch_size: 8
    augmentation: lsj
    return_masks: true
    return_bboxes: true
    return_labels: true
    filter_empty: true 
    min_bbox_size: 1.0 
    use_crowd: false  

  valid_dataset:
    images: ${dataset.data_root}/images
    ann_file: ${dataset.data_root}/annotations/valid.json
    size: [512, 512]
    batch_size: 8
    return_masks: true
    return_bboxes: true
    return_labels: true

  eval_dataset:
    images: ${dataset.data_root}/images
    ann_file: ${dataset.data_root}/annotations/valid.json
    size: [512, 512]
    batch_size: 8
    return_masks: true
    return_bboxes: true
    return_labels: true

  mean: [133.488, 133.488, 133.488]
  std: [26.903, 26.903, 26.903]