dataset_path:       ../datasets/HuBMAP_HPA_2022

train_images:       ${dataset_path}/train_images
train_annotations:  ${dataset_path}/train_annotations
test_images:        ${dataset_path}/test_images

train_csv:          ${dataset_path}/train.csv
test_csv:           ${dataset_path}/test.csv

save_path:          ../models/HuBMAP_HPA_2022/convnext_upernet

seed:           3407
n_folds:        5
model_name:     [MORI]-[convnext_upernet]-1024x512x2-norm[255_mean_std_v2]-aug[heavy3+]-[lung-g1]
group:          [lung-g1]-[convnext_upernet]-aug[heavy3+]-1024x512x2

tiles:          True
img_size:       [1024, 1024]
tile_size:      512
stride:         ???

train_bs:       1
valid_bs:       1
epochs:         1
lr:             1e-4
wd:             1e-6

scheduler:      CosineAnnealingLR
min_lr:         1e-6
T_max:          ???
T_0:            25
warmup_epochs:  0

backbone:       ???
num_classes:    1
tta:            True

device:         cuda:1

