defaults:
  - _self_

model_checkpoint:
  type: ModelCheckpoint
  dirpath: ./checkpoints
  filename: "best"
  monitor: "metrics/valid/mAP"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

progress_bar:
  type: ProgressBar
  refresh_rate: 5

instance_visualizer:
  type: InstanceVisualizer
  inst_types: [instance, overlap, visible]
  ncols: 5
  show_bboxes: False

flops: 
  type: FlopsLogger
  input_size: [1, 3, 512, 512]
  max_depth: 2


