# @package _global_

defaults:
  - _self_
  - dataset: worms
  - model: model/iaunet/iaunet
  - model/encoder: resnet/resnet_50
  - logger: log
  - trainer: gpu
  - run: default
  - hydra: default

test: True

seed: 3407
job_id: null
run_id: null