# @package _global_

defaults:
  - _self_
  - dataset: revvity_25
  - model: v2/iaunet-r50
  
  - logger: log # group_logger # log, wandb
  - trainer: gpu
  - run: default
  - hydra: default
  - callbacks: default


train: True
test: True

num_workers: 2
seed: 3407
job_id: null
run_id: null
