# @package _global_

defaults:
  - _self_
  - dataset: worms

  - model: model/iaunet/iaunet
  - model/encoder: resnet/resnet_50
  - model/decoder: iadecoder
  - model/head/instance_head: instance_head # ??? this is dumb

  - logger: log
  - trainer: ddp
  - run: default
  - hydra: default

  - callbacks: default


train: True
test: True

seed: 3407
job_id: null
run_id: null