# @package _global_

defaults:
  - _self_
  - dataset: worms

  - model: model/iaunet/iaunet
  # - model/encoder: resnet/resnet_50
  # - model/encoder: swin/swin_b

  - logger: log
  - trainer: ddp
  - run: default
  - hydra: default

  - callbacks: default


train: True
test: True

seed: 3407
job_id: null
run_id: null


# the model folder should have a .yaml config file per model variation
# hydra allows to change the config on runtime if needed