# @package _global_
defaults:
 - model/default
 - _self_

model:
  model_name: iaunet-swin-s
  type: iaunet_v2

  # model params.
  encoder: 
    type: SwinTransformer
    embed_dim: 96
    depths: [2, 2, 18, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 7
    mlp_ratio: 4
    qkv_bias: True
    drop_path_rate: 0.3
    patch_norm: True
    pretrained: True
    out_indices: [0, 1, 2, 3]
    pretrain_img_size: 224
    
  decoder: 
    # pixel decoder config.
    type: iadecoder_ml
    n_levels: 4

    mask_branch:
      type: MaskStackedConv # opt: MaskDoubleConv, MaskStackedConv
      dim: 256
      num_convs: 2

    instance_branch:
      type: InstStackedConv # opt: InstDoubleConv, InstStackedConv
      dim: 256
      num_convs: 2
    
    # transformer decoder config.
    num_queries: 100
    num_classes: 1
    hidden_dim: 256
    nheads: 8
    dec_layers: 1   # transfomer decoder layers per model decoder layer.
    dropout: 0.1
    pre_norm: false
    dim_feedforward: 2048


  # model loading and saving.
  load_pretrained: false
  weights: ''
  # TODO: to callbacks
  save_checkpoint: true
  save_model_files: true
  load_from_files: false
  model_files: ''

  # model training params.
  solver:
    optimizer:
      type: AdamW
      lr: 0.0001
      weight_decay: 0.05
    backbone_lr_multiplier: 0.1
    embedding_weight_decay: 0.0

  scheduler:
    type: CosineAnnealingLR
    eta_min: 1.0e-06
    T_max: 16000
    verbose: false
